export const ErrorConstant = Object.freeze({
  DEFAULT: {
    FAILED: 'FAILED',
  },
  TEMPLATE: {
    NOT_FOUND: 'NOT_FOUND',
  },
  AUTH: {
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
    UNAUTHORIZED: 'UNAUTHORIZED',
  },
  RENTOUT: {
    NOT_EXIST_RENTALNEWS: 'NOT_EXIST_RENTALNEWS',
  },
  CREATE: {
    OK: 'CREATE_OK',
    FAILED: 'CREATE_FAILED',
  },
  UPDATE: {
    OK: 'UPDATE_OK',
    FAILED: 'UPDATE_FAILED',
  },
  DELETE: {
    OK: 'DELETE_OK',
    FAILED: 'DELETE_FAILED',
  },
  GET: {
    OK: 'GET_OK',
    FAILED: 'GET_FAILED',
  },
  AUTHORIZATION: {
    UNAUTHORIZED: 'ERROR_A1',
    UNAUTHENTICATED: 'ERROR_A2',
    LOGGED_IN: 'ERROR_A3',
    JWT_EXPIRE: 'ERROR_A4',
    JWT_NOT_EXIST: 'ERROR_A5',
    SIGNATURE_RECOVERY_FAILED: 'ERROR_A6',
    YOU_ARE_UNAUTHORIZED: 'ERROR_A7',
    YOU_DONT_HAVE_ROLE_INVESTOR: 'ERROR_A8',
    YOU_DONT_HAVE_ROLE_PROJECT_OWNER: 'ERROR_A9',
    YOU_DONT_HAVE_ROLE_ADMIN: 'ERROR_A10',
    YOU_DONT_HAVE_ROLE_SUB_ADMIN: 'ERROR_A11',
  },
  VALIDATION: {
    FAILED: 'ERROR_V1',
    INVALID_TIME: 'ERROR_V2',
    START_TIME_MUST_LESS_THAN_END_TIME: 'ERROR_V3',
    START_TIME_MUST_GREATER_THAN_NOW: 'ERROR_V4',
    THE_WALLET_ADDRESS_THAT_YOU_INPUT_IN_FRACTAL_IS_NOT_CORRECT: 'ERROR_V5',
  },
  ERROR: {
    INTERNAL_ERROR: 'ERROR_E1',
    NOT_EXIST: 'ERROR_E2',
    DULPLICATED: 'ERROR_E3',
    DEPLOYED: 'ERROR_E4',
    SIGNATURE_MISMATCH: 'ERROR_E5',
    EXCEED_LIMIT: 'ERROR_E6',
  },
});
