export enum EQuestionDifficultyLevel {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum EQuestionStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
}

export enum EQuestionType {
  PROGRAMMING = 'PROGRAMMING',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  TRUE_FALSE = 'TRUE_FALSE',
  FILL_IN_THE_BLANK = 'FILL_IN_THE_BLANK',
  SHORT_ANSWER = 'SHORT_ANSWER',
  MATCHING = 'MATCHING',
  ESSAY = 'ESSAY',
  CODE_SNIPPET = 'CODE_SNIPPET',
  MULTIPLE_ANSWER = 'MULTIPLE_ANSWER',
  ORDERING = 'ORDERING',
  EQUATION = 'EQUATION',
  HOTSPOT = 'HOTSPOT',
  QUIZ = 'QUIZ',
}
